module org{ 
      module smark{ 
	        module corbaintro{ 
	        	 module service{ 
	        		 module corba{ 
	        			interface HelloService{ 
				                string sayHello(); 
				                oneway void shutdown(); 
				        }; 
	 				 };
	 			 };
	        }; 
	  };
};

